


'''
Exercise 2   The numbers generated by random.random are supposed to be uniform 
between 0 and 1; that is, every value in the range should have the same 
probability.
Generate 1000 numbers from random.random and plot their PMF and CDF. Is the 
distribution uniform?
'''

import random
import numpy
import thinkstats2
import thinkplot

# setting a seed
# comment this out if you want different results
random.seed(100)

random1000 = []

# generating 1000 random numbers
for i in range(1000):
	random1000.append(random.random())

#print(random1000)
#print(str(numpy.mean(random1000)))

PMF = thinkstats2.MakePmfFromList(random1000, label='random.random PMF')

####
'''
a = [1,2,2,3,3,3,4,4,4,4,5,5,5,6,6,7]
PMF = thinkstats2.MakePmfFromList(a, label='lalala')
'''
####

thinkplot.PrePlot()
thinkplot.Hist(PMF)
thinkplot.Config(xlabel='random.random PMF', ylabel='probability', axis=[0.0,1.0,0.0000,0.002])
thinkplot.Show()

#print('Mean of random 1000 numbers is = ' + str(PMF.Mean()))

CDF = thinkstats2.MakeCdfFromList(random1000, label='random.random CDF')

thinkplot.PrePlot()
thinkplot.Cdf(CDF)
thinkplot.Config(xlabel='random.random CDF', ylabel='percent')
thinkplot.Show()



